apiVersion: v1
kind: Service
metadata:
  name: system2-client-service
spec:
  type: ClusterIP # Internal access, external via port-forward
  selector:
    app: system2-client
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
