apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  type: ClusterIP # Internal load balancing, only accessible within cluster
  selector:
    app: system2-rag
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 8100
